# Generated by Django 4.2.3 on 2023-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Тег сайта')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('ua', 'Українська')], default=('ru', 'Русский'), max_length=50, verbose_name='Язык')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('UAH', 'Гривна'), ('USD', 'Доллар')], default=('RUB', 'Рубль'), max_length=50, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Локализация',
                'verbose_name_plural': 'Локализация',
            },
        ),
    ]
