# Generated by Django 4.2.3 on 2025-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_alter_sitesettings_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('ua', 'Українська')], default=('ru', 'Русский'), max_length=50, verbose_name='Язык'),
        ),
    ]
