# Generated by Django 4.2.5 on 2025-02-28 10:42

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание акции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='discounts/', verbose_name='Изображение баннера')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Размер скидки (%)')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Повторение скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-start_date'],
            },
        ),
    ]
