# Generated by Django 4.2.5 on 2025-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='image',
        ),
        migrations.AddField(
            model_name='discount',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма бонуса'),
        ),
        migrations.AddField(
            model_name='discount',
            name='bonus_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бонус-код'),
        ),
        migrations.AddField(
            model_name='discount',
            name='desktop_banner',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/', verbose_name='Баннер (десктоп) — 360x612'),
        ),
        migrations.AddField(
            model_name='discount',
            name='has_bonus',
            field=models.BooleanField(default=False, verbose_name='Включить бонус'),
        ),
        migrations.AddField(
            model_name='discount',
            name='has_bonus_code',
            field=models.BooleanField(default=False, verbose_name='Включить бонус-код'),
        ),
        migrations.AddField(
            model_name='discount',
            name='mobile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/', verbose_name='Баннер (мобайл) — 360x220'),
        ),
        migrations.AddField(
            model_name='discount',
            name='show_timer',
            field=models.BooleanField(default=False, verbose_name='Показывать таймер обратного отсчёта'),
        ),
    ]
