# Generated by Django 4.2.5 on 2025-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_remove_discount_image_discount_bonus_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='promo_code',
            new_name='promo',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='bonus_amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='bonus_code',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='has_bonus',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='has_bonus_code',
        ),
        migrations.AddField(
            model_name='discount',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Включить скидку'),
        ),
        migrations.AddField(
            model_name='discount',
            name='has_promo',
            field=models.BooleanField(default=False, verbose_name='Включить промокод'),
        ),
    ]
