# Generated by Django 4.2.5 on 2025-04-25 09:05

import django.core.validators
from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_rename_promo_code_discount_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, help_text='До 300 символов. Используется для превью или баннера.', null=True, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='desktop_banner',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WebP, 360x600px, до 500KB.', null=True, upload_to='discounts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Баннер (десктоп)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, help_text='Значение от 0 до 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки (%)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Показывать скидку'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='has_promo',
            field=models.BooleanField(default=False, verbose_name='Показывать промокод'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Акция активна'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='mobile_banner',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WebP, 360x220px, до 300KB.', null=True, upload_to='discounts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Баннер (мобайл)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='promo',
            field=models.CharField(blank=True, help_text='Если применим. Уникальный.', max_length=50, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Повторение акции'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='show_timer',
            field=models.BooleanField(default=False, verbose_name='Показать таймер'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(help_text='Короткое название акции (до 75 символов)', max_length=75, verbose_name='Название акции'),
        ),
    ]
