# Generated by Django 4.2.5 on 2025-02-26 14:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0013_alter_course_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи.', max_length=255, verbose_name='Заголовок')),
                ('rich_content', ckeditor.fields.RichTextField(help_text='Форматируемый текст статьи.', verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для статьи.', null=True, upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=False, help_text='Отметьте, если статья должна быть опубликована.', verbose_name='Опубликовано')),
                ('courses', models.ManyToManyField(blank=True, help_text='Выберите курсы, к которым относится эта новость.', to='main.course', verbose_name='Связанные курсы')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
