# Generated by Django 4.2.5 on 2025-04-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_course_apps'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
    ]
