# Generated by Django 4.2.5 on 2025-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_course_apps'),
        ('blog', '0002_rename_article_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1, help_text='Введите краткое описание статьи.', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Выберите курсы, к которым относится эта статья.', to='main.course', verbose_name='Связанные курсы'),
        ),
    ]
