# Generated by Django 4.2.30 on 2026-07-13 20:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_description_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rich_content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Форматируемый текст статьи.', verbose_name='Текст статьи'),
        ),
    ]
