docRoot                   $VH_ROOT/html/
enableGzip                1

errorlog $VH_ROOT/old.mycomputer.education/logs/error.log {
  useServer               1
  logLevel                WARN
  rollingSize             10M
}

index  {
  useServer               1
  indexFiles              index.html
}

scripthandler  {
  add                     lsapi:lsphp html
}

context /.well-known/ {
  location                /usr/local/lsws/old.mycomputer.education/html/.well-known/
  allowBrowse             1
  addDefaultCharset       off
}

context /admin-static/ {
  location                /usr/local/lsws/old.mycomputer.education/html/server/static/
  allowBrowse             1
  addDefaultCharset       off
}

context /media/ {
  location                /usr/local/lsws/old.mycomputer.education/html/server/media/
  allowBrowse             1
  addDefaultCharset       off
}

context /api/ {
  type                    appserver
  location                /usr/local/lsws/old.mycomputer.education/html/server/
  binPath                 /usr/local/lsws/fcgi-bin/lswsgi
  appType                 wsgi
  startupFile             server/wsgi.py
  env                     PYTHONPATH=/usr/local/lsws/old.mycomputer.education/html/lib/python3.10:/usr/local/lsws/old.mycomputer.education/html/server
  env                     LS_PYTHONBIN=/usr/local/lsws/old.mycomputer.education/html/bin/python
  addDefaultCharset       off
}

context / {
  location                /usr/local/lsws/old.mycomputer.education/html/client/
  allowBrowse             1
  indexFiles              index.html

  rewrite  {
    enable                1
    rules                 <<<END_RULES
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{REQUEST_URI} !/admin-static/
RewriteCond %{REQUEST_URI} !/media/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /index.html [L]
END_RULES
  }
  addDefaultCharset       off
}

rewrite  {
  enable                  1
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/old.mycomputer.education/privkey.pem
  certFile                /etc/letsencrypt/live/old.mycomputer.education/fullchain.pem
  certChain               1
}
