docRoot                   $VH_ROOT/html/
enableGzip                1

errorlog $VH_ROOT/old.mycomputer.education/logs/error.log {
  useServer               1
  logLevel                WARN
  rollingSize             10M
}

index  {
  useServer               1
  indexFiles              index.html
}

scripthandler  {
  add                     lsapi:lsphp html
}

context /.well-known/ {
  location                /usr/local/lsws/old.mycomputer.education/html/.well-known/
  allowBrowse             1
  addDefaultCharset       off
}

context /admin-static/ {
  location                /usr/local/lsws/old.mycomputer.education/html/server/static/
  allowBrowse             1
  addDefaultCharset       off
}

context /media/ {
  location                /usr/local/lsws/old.mycomputer.education/html/server/media/
  allowBrowse             1
  addDefaultCharset       off
}

context /api/ {
  type                    appserver
  location                /usr/local/lsws/old.mycomputer.education/html/server/
  binPath                 /usr/local/lsws/fcgi-bin/lswsgi
  appType                 wsgi
  startupFile             server/wsgi.py
  addDefaultCharset       off
}

context / {
  location                /usr/local/lsws/old.mycomputer.education/html/client/
  allowBrowse             1
  indexFiles              index.html

  rewrite  {
    enable                1
    rules                 <<<END_RULES
RewriteRule ^sitemap\.xml$ /api/sitemap.xml [R=302,L]

RewriteCond %{REQUEST_URI} ^/course/([0-9]+)/?$
RewriteCond /usr/local/lsws/old.mycomputer.education/html/client/prerender/course/%1.html -f
RewriteRule ^course/([0-9]+)/?$ /prerender/course/$1.html [L]

RewriteCond %{REQUEST_URI} ^/?$
RewriteCond /usr/local/lsws/old.mycomputer.education/html/client/prerender/home.html -f
RewriteRule ^$ /prerender/home.html [L]

RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{REQUEST_URI} !/admin-static/
RewriteCond %{REQUEST_URI} !/media/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /index.html [L]
END_RULES
  }
  extraHeaders             <<<END_HEADERS
Header always set X-Frame-Options "DENY"
Header always set X-Content-Type-Options "nosniff"
Header always set Referrer-Policy "same-origin"
Header always set Strict-Transport-Security "max-age=3600"
END_HEADERS
  addDefaultCharset       off
}

rewrite  {
  enable                  1
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/old.mycomputer.education/privkey.pem
  certFile                /etc/letsencrypt/live/old.mycomputer.education/fullchain.pem
  certChain               1
}
